<?php
echo "<!DOCTYPE html>\n";
echo "!-- saved from url=(0018)https://www.xingtao.tk -->\n";
echo "html>\n";
echo "head>\n";
echo "meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n";
echo "meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes\">\n";
echo "link rel=\"shortcut icon\" href=\"http://wuxingt.com/favicon.ico\">\n";
echo "!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"./wuxingt_files/css.css\"> -->\n";
echo "link href='http://fonts.useso.com/css?family=Oxygen:300,400,700&subset=latin,latin-ext' rel='stylesheet'>\n";
echo "script type=\"text/javascript\" src=\"./wuxingt_files/jquery-1.7.2.min.js\"></script>\n";
echo "script type=\"text/javascript\" async=\"\" src=\"./wuxingt_files/ga.js\"></script>\n";
echo "script type=\"text/javascript\" src=\"./wuxingt_files/geren/js/global.js\"></script>\n";
echo "script type=\"text/javascript\">\n";
echo "     var wuxingt = wuxingt || {};\n";
echo "     \n";
echo "       wuxingt[\"type\"] = \"prod\";\n";
echo "     \n";
echo "</script><style type=\"text/css\"></style>\n";
echo "   \n";
echo "link rel=\"stylesheet\" href=\"./wuxingt_files/index.css\" media=\"screen\" charset=\"UTF-8\" type=\"text/css\">\n";
echo "title>wuxingt</title>\n";
echo " \n";
echo " </head>\n";
echo "<body ontouchstart=\"\">\n";
echo "   <div id=\"header\"></div>\n";
echo "   <div id=\"body\" class=\"clearfix\">\n";
echo " <div id=\"wuxingt\" style=\"display: block;\">\n";
echo "     <div id=\"banner\">\n";
echo "            <div id=\"wuxingt-logo\">\n";
echo "                 <div class=\"logo-wuxingt\">\n";
echo "                       <div class=\"logo-content themeable\">\n";
echo "                            <div class=\"logo-text\">\n";
echo "                             <div class=\"LOGO-b\"></div></div>\n";
echo "                            <div class=\"logo-pic\"><img src=\"./wuxingt_files/avatar.png\"></div>\n";
echo "                        </div>\n";
echo "                     </div></div>\n";
echo "           <div id=\"wuxingt-text\">wuxingt</div>\n";
echo "   </div>\n";
echo "   <div class=\"line-break\"></div>\n";
echo "   <div id=\"projects\">\n";
echo "     <a href=\"./wuxingt_files/geren/index.html\">Exercises</a>\n";
echo "     <br>\n";
echo "     <a href=\"\">New Programs</a>\n";
echo "     <br>\n";
echo "     <a href=\"./wuxingt_files/geren/about-tao.html\">About 简历及作品</a>\n";
echo "   </div>\n";
echo "   <div id=\"footer-links\">\n";
echo "<ul style=\"height:105px;margin:0px;padding:0px\">\n";
echo "   <li id=\"sina-weibo\" class=\"sns_item\"><a class=\"sns_link\" href=\"http://weibo.com/u/1721747541\" target=\"_blank\"><span class=\"logo_icon\"></span></a></li>\n";
echo "<li id=\"my-tecent\" class=\"sns_item\"><a class=\"sns_link\" href=\"http://t.qq.com/misswxt\" target=\"_blank\"><span class=\"logo_icon\"></span></a></li>\n";
echo "<li id=\"my-email\" class=\"sns_item\"><a class=\"sns_link\" href=\"mailto:540850871@qq.com\" target=\"_blank\"><span class=\"logo_icon\"></span></a></li>\n";
echo "</ul>\n";
echo "/div>\n";
echo " </div>\n";
echo "/div>\n";
echo "div id=\"Bgbanner\">\n";
echo "        <dl id=\"iPrs\">\n";
echo "   <dt>\n";
echo "   <em id=\"pp1\"></em>\n";
echo "   <em id=\"pp2\"></em>\n";
echo "   <em id=\"pp3\"></em>\n";
echo "   </dt>\n";
echo "   <dd></dd></dl>\n";
echo "/div>\n";
echo "<div id=\"footer\"></div>\n";
echo "script type=\"text/javascript\" src=\"./wuxingt_files/jquery.min.js\"></script>\n";
echo "!--[if lt IE 9]><script>wuxingt = wuxingt || {}; wuxingt.isIE = true;</script><![endif]-->\n";
echo "   \n";
echo "script type=\"text/javascript\" charset=\"UTF-8\" src=\"./wuxingt_files/index.js\"></script>\n";
echo "   \n";
echo "\n";
echo "</body></html>\n";
?>